[package]
name = "jot"
version = "0.1.0"
edition = "2021"
authors = ["araekiel"]

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
confy = "0.4.0"
dialoguer = "0.10.1"
serde = { version = "1.0.142", features = ["derive"] }
