[package]
name = "jot"
version = "0.1.0"
edition = "2021"
authors = ["araekiel"]

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
toml = "0.5.9"
clap = { version = "3.2.15", features = ["derive"] }
directories = "4.0.1"
fs_extra = "1.2.0"
